### ISSUE TITLE
Where in admin panel ?

### ISSUE THREAD

**Issue by bonnebulle** [robertotravagliante/string-replacer#1]
Sorry am not finding the plugin admin panel or page you describe in the README file
This plugin can be very helpful when I cant Grep/Sed from my terminal...
Thanks for all

**Comment by robertotravagliante** [comment]
Have you clicked on the link of the string-replacer plugin? (as showed in one of my attached screens).Please, let me know. I will be very glad to support you.Roberto Travagliante - https://www.travagliante.com Il giorno 29 mag 2024, alle ore 01:27, vincent_b ***@***.***> ha scritto:﻿
Sorry am not finding the plugin admin panel or page you describe in the README file
This plugin can be very helpful when I cant Grep/Sed from my terminal...
Thanks for all

**Comment by bonnebulle** [comment]
Hello
Not, I dont see the button
(and yes the plugin is enable ;) )
and cant find a screenshoot to help me (image attached, by mail ? cant see it from here -- github) 
Thanks

**Comment by robertotravagliante** [comment]
Sorry, I put these screenshots here. Please, let me know.


![image0](https://github.com/robertotravagliante/string-replacer/assets/38438568/8e98156f-4858-49b1-b3ab-9fb6742aeba2)
![image1](https://github.com/robertotravagliante/string-replacer/assets/38438568/cd81ad5e-590a-4665-911a-ad89c572477b)
![image2](https://github.com/robertotravagliante/string-replacer/assets/38438568/828a225e-2972-4df8-8278-2da1ba09ed47)

**Comment by bonnebulle** [comment]
Ok, I was not searching the right way... not in plugin itself but in the left-side menu !
Thanks for your patience and detail !
This works great !
Have a good time

**Comment by robertotravagliante** [comment]
Perfect! If you need further help,  don't hesitate to ask me.
Thank you for using it.
